services:
  app:
    container_name: ${CONTAINER_NAME:-badmintion-shop}
    image: ${APP_IMAGE:-badmintion-shop:latest}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_PORT: ${CONTAINER_PORT:-8080}
      # Đường dẫn model CLIP cho DJL Java (khai báo trong .env hoặc trực tiếp ở đây)
      # app.search.clip.model-path=/home/ec2-user/models/clip-vit-base-patch32
      # RABBITMQ_ADDRESSES should be set in .env, e.g. amqp://user:pass@rabbitmq-local:5672
    ports:
      - "${HOST_PORT:-80}:${CONTAINER_PORT:-8080}"
    depends_on:
      elasticsearch:
        condition: service_started
      rabbitmq-local:
        condition: service_started
      redis-local:
        condition: service_started

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq-local:
    container_name: rabbitmq-local
    image: rabbitmq:3-management
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: qwwvmeiz
      RABBITMQ_DEFAULT_PASS: EuohgWGTM2VGE7APABCoFP-rrCOXccgW
    ports:
      - "5672:5672"
      - "15672:15672"

  redis-local:
    container_name: redis-local
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    command: ["sh", "-c", "redis-server --requirepass gQAAAAAAARpKAAIncDEwMmMwZGIzNjBlNTA0ZmViOTRhNTI0NjVlN2NkNDYzM3AxNzIyNjY"]
    ports:
      - "6379:6379"